<?php
/**
 * Created by PhpStorm.
 * User: carl
 * Date: 16/07/17
 * Time: 10:34
 */

// can this fail?
$total = Mage::getModel("checkout/session")->getQuote()->getGrandTotal();

$laybuy_payments = FALSE;

if($total){
    $laybuy_payments = number_format( ($total / 6), 2, '.', ',');
}

?>
<ul class="form-list" id="payment_form_<?php echo $this->getMethodCode(); ?>" style="display: none;">
    <li>
        <div style="padding: 10px 0;">
            <img style="display:inline-block;max-width: 200px;  vertical-align: middle" src="https://www.laybuy.com/images/laybuy-button.png" alt="">
            <?php if($laybuy_payments): ?>
            <h4 style="display:inline-block;padding-left: 15px">6 interest free payments from $<?= $laybuy_payments; ?></h4>
            <?php endif; ?>
        </div>
    
        <p>Laybuy lets you receive your purchase now and spread the total cost over 6 weekly automatic payments. Interest free.</p>
        <p>Available to NZ, AU or UK residents who are 18 years and over and have a valid debit or credit card.</p>
        <p>By selecting &lsquo;LAYBUY&rsquo; you will be redirected to Laybuy to complete your order</p>
    </li>
</ul>

